### ISSUE TITLE
specify room via msg parameter

### ISSUE THREAD

**Issue by arakno76** [PointSource/node-red-contrib-sse#8]
Is it possibile to configure the sse node dinamically? It could be very useful to allow specificying a msg.room in a function block and use the same sse node for several rooms, as result of a parametrized flow.
Thanx

**Comment by nima-yz** [comment]
Currently, that is not possible but I believe that is you definitely have a point so I might add that functionality in future versions.

**Comment by arakno76** [comment]
Ok Thanx,
I made an enhanced version with this feature, you can find here: https://github.com/arakno76/sse-node-red
I needed it for a production site, so I modified it by myself, leaving your copyright notice
